### ISSUE TITLE
enable soong tests during building

### ISSUE THREAD

**Issue by unicornx** [aosp-riscv/platform_manifest#1]
Currently, build can only pass with "m --skip-ninja --skip-soong-tests".

We hope it can pass build with "m --skip-ninja" and enable soong tests.

On how to setup building env, refer to notes: <https://github.com/aosp-riscv/working-group/blob/master/articles/20211029-howto-setup-build-env.md>. And in this note, the git repo is from gitee, not github, but I hope they have been mirrored. Any question please let me know.

**Comment by realShengYao** [comment]
Update:

I'm still working on getting familiar with the architecture of AOSP and its components. I'm trying to figure out how to enable the soong tests.

**Comment by unicornx** [comment]
> Update:
> 
> I'm still working on getting familiar with the architecture of AOSP and its components. I'm trying to figure out how to enable the soong tests.

You can refer to following two to accelerate your work:
- <https://github.com/riscv-android-src>: RVI Android SIG source repo， which is the latest open source from T-head, based on AOSP 10 till now.
- <https://github.com/T-head-Semi/aosp-riscv>, which is also open-sourced by T-head, but a bit older early this year.

**Comment by unicornx** [comment]
> Update:
> 
> I'm still working on getting familiar with the architecture of AOSP and its components. I'm trying to figure out how to enable the soong tests.

some articles about soong build I summarized before @ <https://github.com/aosp-riscv/working-group/tree/master/articles>, hope do help for you.

**Comment by realShengYao** [comment]
Thanks, I'll take a look.

**Comment by realShengYao** [comment]
> Currently, build can only pass with "m --skip-ninja --skip-soong-tests".
> 
> We hope it can pass build with "m --skip-ninja" and enable soong tests.
> 
> On how to setup building env, refer to notes: https://github.com/aosp-riscv/working-group/blob/master/articles/20211029-howto-setup-build-env.md. And in this note, the git repo is from gitee, not github, but I hope they have been mirrored. Any question please let me know.

Update:

The soong tests part is already enabled and the building is successful. I'll upload the patches later.

**Comment by realShengYao** [comment]
Update:

Already fixed the problem by editing the package [aosp-riscv/platform-build-bazel](https://github.com/aosp-riscv/platform-build-bazel) and [aosp-riscv/platform_build_soong](https://github.com/aosp-riscv/platform_build_soong). 

Follow the link to see my pull request for fixing this issue.
[Pull request for aosp-riscv/platform_build_soong](https://github.com/aosp-riscv/platform_build_soong/pull/1)
[Pull request for aosp-riscv/platform-build-bazel](https://github.com/aosp-riscv/platform-build-bazel/pull/1)

Now, the build could be completed with the command "m --skip-ninja" following the [newest build process](https://github.com/aosp-riscv/working-group/blob/master/docs/howto-setup-build-env.md).

**Comment by unicornx** [comment]
closed due to we are not workiong on this.
